global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9100"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "meilisearch"
    static_configs:
      - targets: ["meilisearch:7700"]

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]
